name: Veracode Static Sandbox Scanner
run-name: Veracode Sandbox Scan - ${{ github.event.client_payload.repository.name }}

concurrency:
  group: ${{ github.event.client_payload.event_type }}-${{ github.event.client_payload.repository.name }}-${{ github.event.client_payload.repository.branch }}
  cancel-in-progress: true

on:
  repository_dispatch:
    types:
      - source-code-sandbox-scan
      - dot-net-sandbox-scan
      - go-sandbox-scan
      - tsql-sandbox-scan
      - plsql-sandbox-scan
      - php-sandbox-scan
      - scala-sandbox-scan
      - dart-sandbox-scan
      - java-sandbox-scan
      - unidentified-lang-sandbox-scan
      - ruby-sandbox-scan

jobs:
  build:
    uses: ./.github/workflows/veracode-build-artifact-for-scanning.yml
    with:
      repository: ${{ github.event.client_payload.repository.full_name }}
      ref: ${{ github.event.client_payload.sha }}
      token: ${{ github.event.client_payload.token }}
      event_name: ${{ github.event.action }}
      build_runs_on: ${{ github.event.client_payload.user_config.build_runs_on }}
      build_packager_image: ${{ github.event.client_payload.user_config.build_packager_image }}
      build_predependency_command: ${{ github.event.client_payload.user_config.build_predependency_command }}
      ruby_version: ${{ github.event.client_payload.user_config.ruby_version }}
      bundle_version: ${{ github.event.client_payload.user_config.bundle_version }}

  sandbox_scan:
    needs: build
    runs-on: ubuntu-latest
    name: sandbox scan

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      
      # get the compiled binary from a previous job
      - name: get archive
        uses: actions/download-artifact@v4
        with:
          name: veracode-artifact
          path: ./veracode_artifact_directory

      # run the policy scan action
      - name: Veracode Upload and Scan Action Step
        uses: veracode/uploadandscan-action@v0.1.7
        id: upload_and_scan
        with:
          appname: ${{ github.event.client_payload.user_config.profile_name }}
          createprofile: true
          policy: ${{ github.event.client_payload.policy_name }}
          version: '${{ github.run_id }}'
          filepath: ./veracode_artifact_directory/
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          createsandbox: true
          sandboxname: GitHub App Scans-${{ github.event.client_payload.repository.branch }}
          failbuild: ${{ github.event.client_payload.user_config.break_build_policy_findings }}
          gitRepositoryUrl: ${{ github.server_url }}/${{ github.event.client_payload.repository.full_name }}
