name: Veracode Static Policy Scanner

on:
  workflow_call:
    inputs:
      profile_name:
        required: true
        type: string
  
jobs:
  policy_scan:
    runs-on: ubuntu-latest
    name: policy scan

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      # get the compiled binary from a previous job
      - name: get archive
        uses: actions/download-artifact@v3
        with:
          name: veracode-artifact
          path: ./veracode_artifact_directory
      
      - name: Get the name of the downloaded files
        run: |
          artifact_file=$(ls -1 ./veracode_artifact_directory | head -n 1)
          echo "veracode_artifact=$artifact_file" >> $GITHUB_ENV
      # run the policy scan action
      - name: Veracoe Upload and Scan Action Step
        uses: veracode/veracode-uploadandscan-action@master
        id: upload_and_scan
        with:
          appname: ${{ inputs.profile_name }}
          createprofile: true
          version: '${{ github.run_id }}'
          filepath: ./veracode_artifact_directory/${{ env.veracode_artifact }}
          vid: '${{ secrets.API_ID }}'
          vkey: '${{ secrets.API_KEY }}'
          scanpollinginterval: 30
          scantimeout: 15
        continue-on-error: false
